from sqlalchemy import Column, BigInteger, Float, ForeignKey
from ..base import Base


class ACS2017CountyData(Base):
    __tablename__ = "acs2017_county_data"

    id = Column(BigInteger, primary_key=True)
    totalpop = Column(BigInteger)
    men = Column(BigInteger)
    women = Column(BigInteger)
    hispanic = Column(Float)
    white = Column(Float)
    black = Column(Float)
    native = Column(Float)
    asian = Column(Float)
    pacific = Column(Float)
    votingagecitizen = Column(BigInteger)
    income = Column(BigInteger)
    incomeerr = Column(BigInteger)
    incomepercap = Column(BigInteger)
    incomepercaperr = Column(BigInteger)
    poverty = Column(Float)
    childpoverty = Column(Float)
    professional = Column(Float)
    service = Column(Float)
    office = Column(Float)
    construction = Column(Float)
    production = Column(Float)
    drive = Column(Float)
    carpool = Column(Float)
    transit = Column(Float)
    walk = Column(Float)
    othertransp = Column(Float)
    workathome = Column(Float)
    meancommute = Column(Float)
    employed = Column(BigInteger)
    privatework = Column(Float)
    publicwork = Column(Float)
    selfemployed = Column(Float)
    familywork = Column(Float)
    unemployment = Column(Float)
    fips_code = Column(BigInteger, ForeignKey("fips.fips_code"))
